### PR TITLE
Fix data frames not counted as consumed

### PR DESCRIPTION
**Pull request by amirlivneh**

### CODE REVIEW

**Comment by amirlivneh** [comment]
I just realized that this issue doesn't affect examples/client.cc because the implementation there calls `ngtcp2_conn_extend_max_stream_offset()` and `ngtcp2_conn_extend_max_offset()` from its `nghttp3_recv_data` callback and does not rely on `nghttp3_conn_read_stream()` to return the consumed data bytes. If this is the expectation apps, then this PR is not needed, but this expectation can be made clearer in the documentation.

**Comment by amirlivneh** [comment]
Looking into it more, the current logic is fine and the documentation is clear enough. The only thing worth looking into is the fact that my changes to the state machine nghttp3_conn.c didn't trigger any test failures. It may be good to add a test to verify that data bytes are not reported as consumed by `nghttp3_conn_read_stream()`.

**Comment by tatsuhiro-t** [comment]
Yeah, DATA payload is purposefully excluded from nconsumed from ngtcp2_conn_read_stream() because it is up to the application that it determines when the data is consumed.  For example, proxy might buffer data until it forwards data to upstream, and the each connection has their own flow control limit, we need to limit the buffer size proxy has to keep.
I'll add more document to ngtcp2_conn_read_stream() in order to describe this.
And I completely agree that the test should be added too.

**Comment by tatsuhiro-t** [comment]
Added unit test via 723c1251d5ca61bc186d005a494d107cb1045308 to verify that consumed does not include DATA.

**Comment by amirlivneh** [comment]
Thank you.

**Pull request closed without merging**
